### ISSUE TITLE
Empty google-credentials.json after build

### ISSUE THREAD

**Issue by gerynugrh** [elishaterada/heroku-google-application-credentials-buildpack#4]
During compile phase, when I read `google-credentials.json`, the file is empty. After further reading I found out that `google-credential.sh` only contain `echo > /app/google-credentials.json`.

Referencing [Build Pack API Documentation](https://devcenter.heroku.com/articles/buildpack-api), turns out build pack should have read env value from `$ENV_DIR` instead from env directly.

#3

**Comment by jh0ker** [comment]
Yes, i can confirm we had this problem as well. With your fork, it works correctly now. Thank you :)
